--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: high_score; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.high_score (
    id bigint NOT NULL,
    score integer DEFAULT 0 NOT NULL
);


ALTER TABLE public.high_score OWNER TO postgres;

--
-- Name: high_score_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.high_score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.high_score_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: high_score; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.high_score (id, score) FROM stdin;
1	9
\.


--
-- Name: high_score_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.high_score_id_seq', 1, true);


--
-- Name: high_score high_score_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.high_score
    ADD CONSTRAINT high_score_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

