/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/highScoreService`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mainGame`; params?: Router.UnknownInputParams; } | { pathname: `/system`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/animations/Clouds`; params?: Router.UnknownInputParams; } | { pathname: `/animations/countDown`; params?: Router.UnknownInputParams; } | { pathname: `/entities/BarrelBox`; params?: Router.UnknownInputParams; } | { pathname: `/entities/FishBox`; params?: Router.UnknownInputParams; } | { pathname: `/entities/Floor`; params?: Router.UnknownInputParams; } | { pathname: `/entities/SharkBox`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EndGame`; params?: Router.UnknownInputParams; } | { pathname: `/screens/GameLoad`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TitleScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/highScoreService`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/mainGame`; params?: Router.UnknownOutputParams; } | { pathname: `/system`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/animations/Clouds`; params?: Router.UnknownOutputParams; } | { pathname: `/animations/countDown`; params?: Router.UnknownOutputParams; } | { pathname: `/entities/BarrelBox`; params?: Router.UnknownOutputParams; } | { pathname: `/entities/FishBox`; params?: Router.UnknownOutputParams; } | { pathname: `/entities/Floor`; params?: Router.UnknownOutputParams; } | { pathname: `/entities/SharkBox`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/EndGame`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/GameLoad`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/TitleScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/highScoreService${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/mainGame${`?${string}` | `#${string}` | ''}` | `/system${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/animations/Clouds${`?${string}` | `#${string}` | ''}` | `/animations/countDown${`?${string}` | `#${string}` | ''}` | `/entities/BarrelBox${`?${string}` | `#${string}` | ''}` | `/entities/FishBox${`?${string}` | `#${string}` | ''}` | `/entities/Floor${`?${string}` | `#${string}` | ''}` | `/entities/SharkBox${`?${string}` | `#${string}` | ''}` | `/screens/EndGame${`?${string}` | `#${string}` | ''}` | `/screens/GameLoad${`?${string}` | `#${string}` | ''}` | `/screens/TitleScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/highScoreService`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/mainGame`; params?: Router.UnknownInputParams; } | { pathname: `/system`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/animations/Clouds`; params?: Router.UnknownInputParams; } | { pathname: `/animations/countDown`; params?: Router.UnknownInputParams; } | { pathname: `/entities/BarrelBox`; params?: Router.UnknownInputParams; } | { pathname: `/entities/FishBox`; params?: Router.UnknownInputParams; } | { pathname: `/entities/Floor`; params?: Router.UnknownInputParams; } | { pathname: `/entities/SharkBox`; params?: Router.UnknownInputParams; } | { pathname: `/screens/EndGame`; params?: Router.UnknownInputParams; } | { pathname: `/screens/GameLoad`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TitleScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
